# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "cifs" ];
  boot.kernelModules = [ "kvm-intel" "fuse" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.wireguard ];

  fileSystems."/" = { 
      device = "/dev/disk/by-uuid/c7728e49-ca0b-48a9-a3b3-d063e43f100f";
      fsType = "ext4";
  };

  fileSystems."/boot" = { 
      device = "/dev/disk/by-uuid/A972-279D";
      fsType = "vfat";
  };

  fileSystems."/data" = {
      device = "/dev/disk/by-label/data";
      fsType = "ext4";
  };

  fileSystems."/syno/home" = {
      device = "//192.168.2.28/home";
      fsType = "cifs";
      # options = ["x-systemd.automount,uid=palesz,vers=3.0,auto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s,credentials=/etc/nixos/smb-secrets"];
      options = ["x-systemd.automount,gid=users,uid=palesz,vers=3.0,auto,credentials=/etc/nixos/secrets/smb-secrets,file_mode=0757,dir_mode=0757"];
  };

  fileSystems."/syno/homes" = {
      device = "//192.168.2.28/homes";
      fsType = "cifs";
      options = ["x-systemd.automount,gid=users,uid=palesz,vers=3.0,auto,credentials=/etc/nixos/secrets/smb-secrets,file_mode=0757,dir_mode=0757"];
  };

  fileSystems."/syno/archive" = {
      device = "//192.168.2.28/archive";
      fsType = "cifs";
      options = ["x-systemd.automount,gid=users,uid=palesz,vers=3.0,auto,credentials=/etc/nixos/secrets/smb-secrets,file_mode=0757,dir_mode=0757"];
  };

  fileSystems."/syno/media1" = {
      device = "//192.168.2.28/media1";
      fsType = "cifs";
      options = ["x-systemd.automount,gid=users,uid=palesz,vers=3.0,auto,credentials=/etc/nixos/secrets/smb-secrets,file_mode=0757,dir_mode=0757"];
  };

  fileSystems."/syno/media2" = {
      device = "//192.168.2.28/media2";
      fsType = "cifs";
      options = ["x-systemd.automount,gid=users,uid=palesz,vers=3.0,auto,credentials=/etc/nixos/secrets/smb-secrets,file_mode=0757,dir_mode=0757"];
  };

  fileSystems."/syno/data" = {
      device = "//192.168.2.28/data";
      fsType = "cifs";
      options = ["x-systemd.automount,gid=users,uid=palesz,vers=3.0,auto,credentials=/etc/nixos/secrets/smb-secrets,file_mode=0757,dir_mode=0757"];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ecf24fbf-7da7-41ea-9a3d-0d7207011e3e"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
